fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 3.3.5     # default: RUBY_VERSION
default_ignores: false  # default: true

ignore: # default: []
  - 'vendor/**/*'

plugins:
  - standard-rails:
      target_rails_version: 7.2.1

Layout/EndOfLine:
  Enabled: False